name: Build and check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - uses: gradle/gradle-build-action@v3

      - name: Check Chrome version
        run: |
          google-chrome --version > chrome_version
      - name: Cache Selenium drivers
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('chrome_version') }}-selenium-driver
          path: |
            ~/.cache/selenium
      
      - run: ./gradlew check
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: build-reports
          path: |
            build/reports
            **/build/reports
